import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

/**
 * API route to serve PSADT documentation data to the client
 * This data is used for syntax highlighting, code completion, and linting.
 */
export async function GET(request) {
  try {
    // Data file path (generated by the parser)
    const dataPath = path.join(process.cwd(), 'data', 'psadt-commands.json');
    
    // Check if data file exists
    if (!fs.existsSync(dataPath)) {
      console.error(`PSADT documentation data file not found: ${dataPath}`);
      return NextResponse.json(
        { error: 'Documentation data not available. Run the parser to generate it.' },
        { status: 404 }
      );
    }
    
    // Read and parse data file
    const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
    
    // Return data
    return NextResponse.json(data);
  } catch (error) {
    console.error('Error serving PSADT documentation data:', error);
    return NextResponse.json(
      { error: 'Error serving documentation data' },
      { status: 500 }
    );
  }
}
